# Legg til informasjon om deg her
# og husk god kodestruktur
authors:
  Roberth Strand:
    navn: Roberth Strand
    posisjon: Senior Consultant
    arbeidsgiver: Crayon AS
    arbeidsoppgaver: Jobber med Azure, automasjon og infrastruktur. 
    epost: me@robstr.dev
    nettside: https://robstr.dev
    twitter: RoberthTweets
    github: RoberthStrand
    facebook:
    bilde: https://secure.gravatar.com/avatar/8df9a5ac37b58842cfdc2b5dbc9092fc?size=150px


####################
#  Her under skal  #
# du ikke redigere #
####################
title:              Skyarkitektur.no
email:              post@skyarkitektur.no
description:        Norsk blogg om skyen
baseurl:            "/"
url:                "https://skyarkitektur.no"
permalink:          /:slug
timezone:           Europe/Oslo

# Social Profiles
twitter_username:   
github_username:    skyarkitektur
facebook_username:  
linkedin_username:  

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-166158735-1 # out your google-analytics code

# Build settings
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
