title:              Skyarkitektur.no
email:              post@skyarkitektur.no
description:        Norsk blogg om skyen
baseurl:            "/"
url:                "https://skyarkitektur.no"
permalink:          /:categories/:title/
timezone:           Europe/Oslo
highlighter: rouge
markdown: kramdown

# Social Profiles
twitter_username:   
github_username:    skyarkitektur
facebook_username:  
linkedin_username:  

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-166158735-1 # out your google-analytics code

# Build settings
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
