title:              Skyarkitektur.no
email:              me@robstr.dev
description:        Norsk blogg om skyen
baseurl:            "/skyarkitektur.no"
url:                "https://skyarkitektur.github.io"

# Authors
authors:
  Roberth Strand:
    display_name: Roberth Strand
    about: Cloud consultant working primarily with Microsoft Azure, automation and infrastructure.
    email: me@robstr.dev
    web: https://robstr.dev
    twitter: RoberthTweets
    github: RoberthStrand
    facebook:
    gravatar: https://secure.gravatar.com/avatar/8df9a5ac37b58842cfdc2b5dbc9092fc?size=150px

# Social Profiles
twitter_username:   RoberthTweets
github_username:    RoberthStrand
facebook_username:  
linkedin_username:  RoberthStrand

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
