title:              Skyarkitektur.no
email:              me@robstr.dev
description:        Norsk blogg om skyen
baseurl:            "/skyarkitektur.no"
url:                "https://skyarkitektur.github.io"

# Authors
authors:
  Roberth Strand:
    name: Roberth Strand
    display_name: Roberth
    gravatar: d7b91766dd6cfae59ca659853f0d3918
    email: me@robstr.dev
    web: https://robstr.dev
    twitter: RoberthTweets
    github: RoberthStrand

# Social Profiles
twitter_username:   RoberthTweets
github_username:    RoberthStrand
facebook_username:  
linkedin_username:  RoberthStrand

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
